FROM prefecthq/prefect:3-python3.12

# Install the dbt adapter
RUN pip install --no-cache-dir prefect[dbt] prefect[docker]

RUN prefect version

ENTRYPOINT ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]