# Pinot drivers would not install!
FROM apachepinot/pinot-superset:latest

USER root

# Install drivers
RUN pip install --no-cache-dir "trino[sqlalchemy]"

ENV ADMIN_USERNAME admin
ENV ADMIN_EMAIL admin@superset.com
ENV ADMIN_PASSWORD password

COPY ./superset_init.sh /superset-init.sh
RUN chmod +x /superset-init.sh
RUN chown superset /superset-init.sh

COPY superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

USER superset
ENTRYPOINT [ "/superset-init.sh" ]